"""Reads method signatures, properties and enum values from Unreal's Python API stub.

The stub (unreal.py, generated by the editor) is not importable as a whole, so
this parses the parts the mock needs. Point UNREAL_STUB at it, or let
fetch_stub.sh download the 5.6 stub from PyPI (package unreal-stub).
"""

import os
import re

DEFAULT_STUB = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.stub', 'unreal', 'unreal.py')


def stub_path():
    return os.environ.get('UNREAL_STUB', DEFAULT_STUB)


def available():
    return os.path.exists(stub_path())


def _split_params(text):
    out, depth, cur = [], 0, ''
    for ch in text:
        if ch in '([{':
            depth += 1
        elif ch in ')]}':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur)
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [p.strip() for p in out]


class Method(object):
    def __init__(self, name, params, is_class):
        self.name = name
        self.params = params          # [(name, has_default)]
        self.is_class = is_class

    def check(self, owner, args, kwargs):
        names = [p for p, _ in self.params]
        if len(args) > len(names):
            raise TypeError('%s.%s takes %d arguments, got %d' % (owner, self.name, len(names), len(args)))
        given = set(names[:len(args)])
        for k in kwargs:
            if k not in names:
                raise TypeError('%s.%s has no argument %r (has %s)' % (owner, self.name, k, ', '.join(names)))
            if k in given:
                raise TypeError('%s.%s got %r twice' % (owner, self.name, k))
            given.add(k)
        for p, has_default in self.params:
            if not has_default and p not in given:
                raise TypeError('%s.%s missing argument %r' % (owner, self.name, p))


class StubClass(object):
    def __init__(self, name, base):
        self.name = name
        self.base = base
        self.methods = {}
        self.properties = set()
        self.enum_values = set()
        self.module = None


class Stub(object):
    def __init__(self, path=None):
        src = open(path or stub_path(), encoding='utf-8-sig').read()
        self.classes = {}
        cur = None
        pending_classmethod = False
        for line in src.splitlines():
            m = re.match(r'^class (\w+)\((\w*)\):', line)
            if m:
                cur = StubClass(m.group(1), m.group(2))
                self.classes[cur.name] = cur
                continue
            if cur is None:
                continue
            if line.strip() == '@classmethod':
                pending_classmethod = True
                continue
            m = re.match(r'^    def (\w+)\((.*)\)(?: -> .*)?:\s*$', line)
            if m:
                params = _split_params(m.group(2))
                is_class = pending_classmethod
                pending_classmethod = False
                if params and params[0] in ('self', 'cls'):
                    params = params[1:]
                parsed = []
                for p in params:
                    pname = p.split(':')[0].split('=')[0].strip()
                    parsed.append((pname, '=' in p))
                if m.group(1) not in cur.methods:
                    cur.methods[m.group(1)] = Method(m.group(1), parsed, is_class)
                continue
            m = re.match(r'^    - \*\*Module\*\*: (\w+)', line)
            if m and cur.module is None:
                cur.module = m.group(1)
                continue
            m = re.match(r'^    - ``(\w+)`` \(', line)
            if m:
                cur.properties.add(m.group(1))
                continue
            m = re.match(r'^    (\w+): (\w+) = \.\.\.', line)
            if m and m.group(2) == cur.name:
                cur.enum_values.add(m.group(1))

    def find_method(self, cls_name, method):
        c = self.classes.get(cls_name)
        while c is not None:
            if method in c.methods:
                return c.methods[method]
            c = self.classes.get(c.base)
        return None

    def has_property(self, cls_name, prop):
        c = self.classes.get(cls_name)
        while c is not None:
            if prop in c.properties or prop in c.methods:
                return True
            c = self.classes.get(c.base)
        return False

    def check_call(self, cls_name, method, args, kwargs):
        m = self.find_method(cls_name, method)
        if m is None:
            raise AttributeError('unreal.%s has no method %s' % (cls_name, method))
        m.check(cls_name, args, kwargs)

    def check_enum(self, cls_name, value):
        c = self.classes.get(cls_name)
        if c is None:
            raise AttributeError('unreal has no enum %s' % cls_name)
        if value not in c.enum_values:
            raise AttributeError('unreal.%s has no value %s' % (cls_name, value))
